services:
  helloworld:
    image: crccheck/hello-world
    container_name: helloworld
  
  nginx:
    image: nginx
    restart: unless-stopped
    container_name: nginx
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
